---


MYSQL_DAEMON: mysql

PACKAGES:
  - python
  - apache2
  - libcairo2-dev
  - libjpeg-dev
  - libjpeg8-dev
  - libjpeg-turbo8-dev
  - libpng-dev
  - libossp-uuid-dev
  - libguac-dev
  - "tomcat{{ TOMCAT_VERSION }}"
  - "tomcat{{ TOMCAT_VERSION }}-common"
  - libtomcat{{ TOMCAT_VERSION }}-java
  - software-properties-common
  - openjdk-{{ JAVA_VERSION }}-jre-headless
  - python-psycopg2
  - mysql-server
  - libmysqlclient-dev
  - libpq-dev
  - python3-pip
  - python3-dev
  - python3-mysqldb
  # Optionals:
  - libfreerdp-dev
  - libpango1.0-dev
  - libssh2-1-dev
  - libtelnet-dev
  - libvncserver-dev
  - libpulse-dev
  - libssl-dev
  - libvorbis-dev
  - libwebp-dev
  - haveged
  - zip
  - unzip


